[package]
name = "rust-egui-tests"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.21.3"
rand = "0.8.5"
egui_extras = "0.21.0"